SOURCES = util.ml symbol.ml label.ml typ.ml basis.ml env.ml ast.ml \
		      lexer.ml debug.ml parser.ml \
          staticbasis.ml static.ml \
		      name.ml lift.ml copyprop.ml \
          quads.ml wasm.ml control.ml copyprop_quads.ml \
		      mips.ml dynamicbasis.ml codegen.ml \
          compile.ml

PACKS = unix
INCDIRS = ~/cs3366/lib/
LIBS = code
RESULT = mc
OCAMLMAKEFILE = ~/.opam/default/lib/ocaml-makefile/OCamlMakefile
include $(OCAMLMAKEFILE)
